### PR TITLE
Merge pull request #29 from stephenoken/pushnoti

### PR DESCRIPTION
**Pull request by ghost**
Pushnoti

### CODE REVIEW

**Comment by ghost** [comment]
so... can we merge this now? 😂

**Comment by stephenoken** [comment]
I don't know... maybe the others should review 😄 this as well

**Comment by harpresing** [comment]
I don’t know man, I see a .DS_Store file there 😄

Where are you these days btw?

**Comment by ghost** [comment]
Test coverage is also a little low... 
I'm in Barcelona at a company that is something like LinkedIn for the german market? And you guys?

**Comment by harpresing** [comment]
Nice man, I'm still in rainy Dublin with a FinTech company! Any plans to visit the old bois?

**Comment by stephenoken** [comment]
Nice,Is the work interesting?. I'm still in Dublin and working in a Travel company. Are you going to make any trips to Dublin?

**Comment by ghost** [comment]
Sounds pretty good what you are doing.. 
The job cold be more exiting. A lot of process and the code is quite old and messy>
I haven't been in Dublin for ages and really want to come for a visit

**Comment by anujsinghdm** [comment]
Hey bitches 🐕

**Comment by ghost** [comment]
whohooo nuuji 🖖

**Comment by anujsinghdm** [comment]
Hey Mickey, you all should come here in the Netherlands.

**Comment by stephenoken** [comment]
Is that an invitation Anuj?!

**Comment by ghost** [comment]
What’s your closest airport?

**Comment by anujsinghdm** [comment]
Yes Stephen, that's an invitation and Mich it's either Schipol or Rotterdam both are like at the same distance from my place.

**Pull request closed without merging**
